### ISSUE TITLE
チャットの設定で失敗しました

### ISSUE THREAD

**Issue by TakayukiOshimaCSC** [TakayukiOshimaCSC/OfficeWorkManual1#2]
マニュアルで解説されているチャットの設定がうまくできませんでした。
掲載されているURLは正しいでしょうか。

**Comment by takayuki-oshima** [comment]
確認しましたが、URL には問題がないようです。
詳しい症状をお知らせください。

**Comment by TakayukiOshimaCSC** [comment]
ネットワークに接続されていませんでした。問題が解消しました。
